---
- name: Removes a cluster from the AI Service and Libvirt/KVM
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  vars:
    delete_generated_assets: false

  tasks:
    - name: Read in variables
      include_vars:
        dir: vars
        extensions:
          - 'yaml'
          - 'yml'

    - name: Delete the VMs in Libvirt
      block:
      - name: Destroy all the VMs
        community.libvirt.virt:
          name: "{{ cluster_name }}-{{ item.name }}"
          state: destroyed
        loop: "{{ cluster_nodes }}"
        loop_control:
          label: "Destroying {{ cluster_name }}-{{ item.name }}"
        ignore_errors: yes

      - name: Delete all the VMs
        community.libvirt.virt:
          name: "{{ cluster_name }}-{{ item.name }}"
          command: undefine
        loop: "{{ cluster_nodes }}"
        loop_control:
          label: "Deleting {{ cluster_name }}-{{ item.name }}"
        ignore_errors: yes

      - name: Delete the VM disks
        file:
          state: absent
          path: "{{ libvirt_base_vm_path }}/{{ cluster_name }}-{{ item.name }}.qcow2"
        loop: "{{ cluster_nodes }}"
        loop_control:
          label: "Deleting {{ libvirt_base_vm_path }}/{{ cluster_name }}-{{ item.name }}.qcow2"

      - name: Reattach devices to host system from VMs
        include_tasks: tasks/libvirt_reattach_devices.yaml
        loop: "{{ cluster_nodes }}"
        loop_control:
          loop_var: node
        when: node.pci_devices is defined

      - name: Delete the Restart touch files
        file:
          state: absent
          path: "{{ generated_asset_directory }}/{{ cluster_name }}/.restarted-{{ cluster_name }}-{{ node.name }}"
        loop: "{{ cluster_nodes }}"
        loop_control:
          loop_var: node

      - name: Delete the RHEL ISO
        file:
          state: absent
          path: "{{ libvirt_base_iso_path }}/rhel7-{{ cluster_name }}.iso"
        when: delete_generated_assets|bool

      - name: Delete the generated content directory
        file:
          state: absent
          path: "{{ generated_asset_directory }}/{{ cluster_name }}/"
        when: delete_generated_assets|bool