---
collections:
  - name: community.crypto
  - name: community.general
  - name: community.libvirt
  - name: ansible.posix
  - name: community.okd
    version: 2.0.1
  - name: kubernetes.core
    version: 2.1.0
