---
- name: Wait for SSH to come up
  wait_for_connection:
    delay: 10
    timeout: 360

- name: Register to RHSM with username and password
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    auto_attach: false
    pool_ids: "{{ rhsm_subscription_pools }}"

- name: Disable all repos
  community.general.rhsm_repository:
    name: '*'
    state: disabled

- name: Enable specific repos
  community.general.rhsm_repository:
    name: "{{ needed_rhel7_repos }}"
    state: enabled

- name: Ensure SELinux is enabled
  selinux:
    state: enabled

- name: Update system packages
  yum:
    name: "*"
    state: latest
    update_cache: yes
  register: update_task_result

- name: Reboot immediately if there were new packages installed
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: update_task_result is changed

- name: Wait for the reboot to complete if there were new packages installed
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: update_task_result is changed
  delay: 10
  register: wait_result
  retries: 3
  until: wait_result is succeeded