- name: Generate per-cluster SSH key if needed
  block:
    - name: Create the key pair
      community.crypto.openssh_keypair:
        path: "{{ generated_asset_directory }}/{{ cluster_name }}/id_rsa"
    - name: Read SSH Key
      set_fact:
        ssh_public_key: "{{ lookup('file', generated_asset_directory+'/'+cluster_name+'/id_rsa.pub') }}"
        ssh_private_key: "{{ lookup('file', generated_asset_directory+'/'+cluster_name+'/id_rsa') }}"
      no_log: true
  when: generate_ssh_key|bool

- name: Read in SSH key
  block:
    - name: Read pre-exising SSH Key
      set_fact:
        ssh_public_key: "{{ lookup('file', ssh_pub_key_path) }}"
        ssh_private_key: "{{ lookup('file', ssh_priv_key_path) }}"
      no_log: true
  when: not generate_ssh_key