---
################################################## Basic Configuration
# generate_ssh_key: true/false, will generate unique key pair if true
generate_ssh_key: true
# ssh_pub_key_path: If 'generate_ssh_key' is false, point to an existing SSH Public Key
ssh_pub_key_path: "~/.ssh/id_rsa.pub"

# This API token is used to automatically download the RHEL 7 ISO - https://access.redhat.com/management/api
rh_offline_api_token: "eyJhb..."

## RHSM Information
rhsm_username: you@example.com
rhsm_password: someSecureString
rhsm_subscription_pools:
  - aSubscriptionPoolID
  - maybeAnotherSubscriptionPoolID

## RHEL User information
rootPassword: someSecureString
user_name: ocpthree
user_password: someSecureString

# cluster_name and cluster_domain will form the cluster base endpoint, eg cluster_name.cluster_domain
# Ensure the DNS A records for {api,api-int,apps,*.apps}.cluster_name.cluster_domain exist
cluster_name: ocp3
cluster_domain: kemo.labs

################################################## Cluster Networking
# cluster_api_vip: an IP or "auto"
cluster_api_vip: 192.168.42.74
# cluster_load_balancer_vip: an IP or "auto"
cluster_load_balancer_vip: 192.168.42.75

################################################## Cluster Node IPAM
# cluster_node_network_ipam: dhcp or static
cluster_node_network_ipam: static
######################### If cluster_node_network_ipam == static:
cluster_node_network_static_dns_servers:
  - 192.168.42.9
  - 192.168.42.10
cluster_node_network_static_dns_search_domains:
  - kemo.labs
cluster_nodes:
  - name: lb
    type: load-balancer
    vm:
      disk_size: 40
      cpu_cores: 2
      cpu_sockets: 1
      cpu_threads: 1
      memory: 8192
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:70
        dhcp: false
        ipv4:
          - address: 192.168.42.60
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: cp-1
    type: control-plane
    vm:
      disk_size: 120
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:71
        dhcp: false
        ipv4:
          - address: 192.168.42.62
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: cp-2
    type: control-plane
    vm:
      disk_size: 120
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:72
        dhcp: false
        ipv4:
          - address: 192.168.42.63
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: cp-3
    type: control-plane
    vm:
      disk_size: 120
      cpu_cores: 4
      cpu_sockets: 1
      cpu_threads: 1
      memory: 16384
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:73
        dhcp: false
        ipv4:
          - address: 192.168.42.64
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: app-1
    type: application-node
    vm:
      disk_size: 120
      cpu_cores: 6
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:74
        dhcp: false
        ipv4:
          - address: 192.168.42.65
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: app-2
    type: application-node
    vm:
      disk_size: 120
      cpu_cores: 6
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:75
        dhcp: false
        ipv4:
          - address: 192.168.42.66
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254
  - name: app-3
    type: application-node
    vm:
      disk_size: 120
      cpu_cores: 6
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
    #pci_devices:
    # A list of strings of PCI devices as reported by `sudo lspci -nn`
    #  - "81:00.0"
    #  - "81:00.1"
    #  - "81:00.2"
    #  - "81:00.3"
    interfaces:
      - name: eth0
        mac_address: 54:52:00:42:69:76
        dhcp: false
        ipv4:
          - address: 192.168.42.67
            prefix: 24
        routes:
          - destination: 0.0.0.0/0
            next_hop_address: 192.168.42.1
            next_hop_interface: eth0
            table_id: 254

# extra_roles [optional]: name roles to run after cluster provisioning
#extra_roles:
#- ocp-operators-deploy-nfd
#- ocp-operators-deploy-gpu-operator

################################################## DO NOT EDIT PAST THIS LINE (unless you know what you're doing)
cluster_skip_verify_tls: true

generated_asset_directory: ./.generated

rhel_sha_sum: 19d653ce2f04f202e79773a0cbeda82070e7527557e814ebbce658773fbe8191

needed_rhel7_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.11-rpms
  - rhel-7-server-ansible-2.9-rpms
  - rh-gluster-3-client-for-rhel-7-server-rpms

needed_packages:
- wget
- git
- net-tools
- bind-utils
- yum-utils
- iptables-services
- bridge-utils
- bash-completion
- kexec-tools
- sos 
- psacct
- openshift-ansible
- docker-1.13.1